[meta]
version = '0.2'
sample = 'CAPERS_EGS_V0.2'

[file_structure]
observations_folder = '/home/vital/Astrodata/CAPERS'
data_folder = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data'
#file_log_headers = ["sample", "id", "file", "MPT_number", "alias", "disp", "pointing", "ext",
#                    "z_med", "z_UNICORN", 'flux_F277W', 'flux_F356W', 'flux_F444W', 'MSA_weight', 'n_nods',
#                    'n_visits', 'visit_1', 'visit_2', 'visit_3', 'eff_exp_time', 'shutter_centering',
#                    "z_aspect_brute", "z_aspect_brute_bound", "z_aspect_points", "z_manual", "z_bands", "z_gaussian", "z_gaussian_err",
#                    "z_best", "zq_best",
#                    "n_emission", "n_doublet", "n_cosmic-ray", "n_absorption", "n_dead-pixel", "n_lines",
#                    "conf_emission", "conf_doublet", "conf_cosmic-ray", "conf_absorption", "conf_dead-pixel",
#                    "file_path"]

#headers_sample = ['flux_F277W', 'flux_F356W', 'flux_F444W', 'MSA_weight', 'n_nods',
#                    'n_visits', 'visit_1', 'visit_2', 'visit_3', 'eff_exp_time', 'shutter_centering']


headers_id = ["sample", "id", "pointing", "MPT_number", "alias", 'ra', 'dec', "disp", "z_med", "z_UNICORN",
               "s2d", 'x1d', 'optext']

headers_sample = ['MSA_weight','n_nods_vis1','n_nods_vis2','n_nods_vis3','eff_exp_time','shutter_centering']

headers_analysis = ["Notes", "z_tier", "z_aspect_key", "z_aspect_xor", "z_aspect_points", "z_manual", "z_bands",
                    "z_gaussian", "z_gaussian_err", "z_best", "zq_quality", "n_emission", "n_doublet", "n_cosmic-ray",
                    "n_absorption", "n_dead-pixel", "n_lines", "conf_emission", "conf_doublet", "conf_cosmic-ray",
                    "conf_absorption", "conf_dead-pixel",
                    "file_path"]

headers_photometry = ["flux_f090w", "fluxerr_f090w",
                        "flux_f105w", "fluxerr_f105w",
                        "flux_f115w", "fluxerr_f115w",
                        "flux_f125w", "fluxerr_f125w",
                        "flux_f140w", "fluxerr_f140w",
                        "flux_f150w", "fluxerr_f150w",
                        "flux_f160w", "fluxerr_f160w",
                        "flux_f200w", "fluxerr_f200w",
                        "flux_f277w", "fluxerr_f277w",
                        "flux_f356w", "fluxerr_f356w",
                        "flux_f410m", "fluxerr_f410m",
                        "flux_f435w", "fluxerr_f435w",
                        "flux_f444w", "fluxerr_f444w",
                        "flux_f606w", "fluxerr_f606w",
                        "flux_f814w", "fluxerr_f814w"]

fits_ext_list = ['s2d.fits', 'x1d.fits', 'x1d_optext.fits']

ext_1d_fits = ['optext', 'x1d']

CAPERs_EGS_redshift_file = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data/CAPERS_EGS_V0.2/CAPERS_yields_v2/CAPERS_EGS_master_yield_v2.csv'
EGS_redshift_headers = ['z_med','z_UNICORN','flux_F277W','MSA_weight','n_nods_vis1','n_nods_vis2','n_nods_vis3','eff_exp_time','shutter_centering']
#UDS_fname= '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data/CAPERS_UDS_V2/CAPERS_yields_v2/CAPERS_UDS_master_yield_v2.csv'
#EGS_fname = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data/CAPERS_EGS_V0.2/CAPERS_yields_v2/CAPERS_EGS_master_yield_v2.csv'
#COSMOS_fname = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data/CAPERS_UDS_V2/CAPERS_yields_v2/CAPERS_COSMOS_master_yield_v2.csv'

prism_R_curve_file = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/source/jwst_nirspec_prism_disp.fits'
prism_bands = '/home/vital/Dropbox/Astrophysics/Data/CAPERS/data/CAPERS_EGS_V0.2/CAPERs_prism_lines_v2.txt'
#redshift_bands = 'CAPERS_prism_bands_redshift.txt'
trace_file =  "capers_trace_coordinates.txt"

lines_redshift = ['H1_1216A',
    'C3_1909A',    'O2_3727A',
    'O2_3730A',    'H1_4342A',
    'H1_4863A',    'O3_4960A',
    'O3_5008A',    'N2_6550A',
    'H1_6565A',    'N2_6585A',
    'S3_9071A',    'S3_9533A',
    'He1_10832A',    'H1_12822A',
    'H1_18756A']

lines_visualize =  ['H1_1216A',
                    'C3_1909A',    'O2_3727A',
                    'O2_3730A',    'H1_4342A',
                    'H1_4863A',    'O3_4960A',
                    'O3_5008A',    'H1_6565A',
                    'He1_5877A',
                    'S3_9071A',    'S3_9533A',
                    'He1_10832A',  'H1_12822A',
                    'H1_18756A']

[data]
norm_flux = 1e-22
default_prism_cfg_section = 'default_prism'
boundary_prism_cfg_section = 'boundary_prism'

[automatic_prism_line_fitting]
O2_3727A_m = "O2_3727A+O2_3730A"
H1_4863A_b = "H1_4863A+O3_4960A+O3_5008A"
H1_6565A_m = "H1_6565A+N2_6585A+N2_6550A+S2_6718A+S2_6733A"
#S2_6718A_m = "S2_6718A+S2_6733A"
He1_10832A_m = "He1_10832A+H1_10941A"

[default_prism_line_fitting]
O2_3727A_m = "O2_3727A+O2_3730A"
Ne3_3870A_m = "Ne3_3870A+H1_3890A"
H1_4342A_b = "H1_4342A+O3_4364A"
H1_4863A_b = "H1_4863A+O3_4960A+O3_5008A"
H1_4863A_m = "H1_4863A+O3_4960A+O3_5008A"
O3_5008A_m = "O3_5008A+O3_4960A"
O3_5008A_b = "O3_5008A+O3_4960A"
H1_6565A_m = "H1_6565A+N2_6585A+N2_6550A"
S2_6718A_m = "S2_6718A+S2_6733A"
O2_7321A_m = "O2_7321A+O2_7332A"
He1_10832A_m = "He1_10832A+H1_10941A"
He1_10832A_b = "He1_10832A+H1_10941A"

[boundary_prism_line_fitting]
O3_4960A_kinem = "O3_5008A"
H1_4862A_kinem = "O3_5008A"
O3_4960A_amp = "expr:O3_5008A_amp/2.91"

[119334_line_fitting]
H1_4863A_b = "H1_4863A+H1_4863A_k-1+O3_5008A+O3_4960A"

H1_4863A_kinem = "O3_5008A"
O3_4960A_kinem = "O3_5008A"
O3_4960A_amp = "expr:O3_5008A_amp/2.91"
H1_4863A_amp = "min:3"

#H1_4342A_b = "H1_4342A+H1_4342A_k-1"
#H1_4342A_k-1_center = 'expr:H1_4342A_center'
#H1_4342A_k-1_sigma = "expr:4*H1_4342A_sigma"
#H1_4342A_amp = "min:1,max:5"

#H1_4342A_b = "H1_4342A+H1_4342A_k-1"
#H1_4342A_kinem = "H1_4863A"
#H1_4342A_k-1_kinem = "H1_4863A_k-1"
#H1_4342A_amp = "min:3"
#H1_4342A_k-1_amp = "min:10"

#H1_4342A_b = "H1_4342A+H1_4342A_k-1"
#H1_4342A_kinem = "H1_4863A"
#H1_4342A_k-1_kinem = "H1_4863A_k-1"
#H1_4342A_amp = "min:3"
#H1_4342A_k-1_amp = "min:10"

H1_4342A_b = "H1_4342A+O3_4363A"
O3_4363A_kinem = "O3_5008A"
O3_4363A_amp = "min:3"

#H1_4342A_b = "H1_4342A+O3_4363A"
#H1_4342A_sigma = "expr:>1.5*O3_4363A_sigma"
##O3_4363A_kinem = "O3_5008A"
##O3_4363A_amp = "min:3"