[meta]
version = '0.1'
sample = 'CAPERS_UDS_V0.1'

[file_structure]
#observations_folder = '/home/vital/PycharmProjects/ceers-data/data/spectra'
observations_folder = '/home/vital/Astrodata/CAPERS'
data_folder = '/home/vital/Dropbox/Astrophysics/Data/CAPERS'
file_log_headers = ["sample", "id", "file", "MPT_number", "alias", "disp", "pointing", "ext",
                    "z_med", "z_UNICORN", 'flux_F277W', 'flux_F356W', 'flux_F444W', 'MSA_weight', 'n_nods',
                    'n_visits', 'visit_1', 'visit_2', 'visit_3', 'eff_exp_time', 'shutter_centering',
                    "z_aspect_brute", "z_aspect_brute_bound", "z_manual", "z_bands", "z_gaussian", "z_gaussian_err",
                    "z_best", "zq_best",
                    "n_emission", "n_doublet", "n_cosmic-ray", "n_absorption", "n_dead-pixel", "n_lines",
                    "conf_emission", "conf_doublet", "conf_cosmic-ray", "conf_absorption", "conf_dead-pixel",
                    "file_path"]

fits_ext_list = ['s2d.fits', 'x1d.fits', 'x1d_optext.fits']

ext_1d_fits = ['optext', 'x1d']

#CEERs_redshift_file = 'CEERS_NIRSpec_MSA_catalog_dr0.9_extended.csv'
CAPERs_redshift_file = '/home/vital/Astrodata/CAPERS/CAPERS_UDS_V0.1/Auxillary_Files/CAPERS_UDS_master_yield_v1.0.csv' #'CEERS_NIRSpec_MSA_catalog_dr0.9_extended.csv'
prism_R_curve_file = 'jwst_nirspec_prism_disp.fits'

prism_bands = 'CAPERS_prism_bands.txt'
redshift_bands = 'CAPERS_prism_bands_redshift.txt'
trace_file =  "capers_trace_coordinates.txt"

[data]
norm_flux = 1e-22
default_prism_cfg_section = 'default_prism'
boundary_prism_cfg_section = 'boundary_prism'

[default_prism_line_fitting]
O2_3729A_m = "O2_3727A+O2_3730A"
O2_3729A_b = "O2_3727A+O2_3730A"
N4_1483A_m = "N4_1483A+O2_3730A"
H1_4862A_b = "H1_4862A+O3_4960A+O3_5008A"
H1_4862A_m = "H1_4862A+O3_4960A+O3_5008A"
O3_5008A_m = "O3_5008A+O3_4960A"
O3_5008A_b = "O3_5008A+O3_4960A"
H1_6565A_m = "H1_6565A+N2_6585A+N2_6550A+S2_6718A+S2_6732A"
H1_6565A_b = "H1_6565A+S2_6718A+S2_6733A"
S2_6718A_m = "S2_6718A+S2_6733A"
O2_7321A_m = "O2_7321A+O2_7332A"
He1_10833A_m = "He1_10833A+H1_10941A"

[boundary_prism_line_fitting]
O3_4960A_kinem = "O3_5008A"
H1_4862A_kinem = "O3_5008A"
O3_4960A_amp = "expr:O3_5008A_amp/2.91"
He1_10833A_b = "He1_10833A+H1_10941A"
H1_10941A_kinem = "He1_10833A"

[s000023419_CAPERS_UDS_P1_s000023419_x1d_optext_line_fitting]
H1_6565A_b = "H1_6565A+H1_6565A_k-1"
H1_6565A_k-1_sigma = "expr:>2*H1_6565A_sigma"
#H1_6565A_k-1_sigma = "expr:>2.0*H1_6565A_sigma"
#H1_6565A_k-2_sigma = "expr:>2.0*H1_6565A_k-1_sigma"

[s000022431_CAPERS_UDS_P1_s000022431_x1d_optext_line_fitting]
He2_1640A_b = "Ne4_1600A+He2_1640A+O3_1664A"
H1_4342A_b = "H1_4342A+O3_4364A"
Ne3_3870A_b = "Ne3_3870A+H1_3889A"
H1_4862A_b = "H1_4862A+O3_4960A+O3_5008A+He1_5016A"
O3_4364A_kinem = "O3_5008A"
O3_4960A_kinem = "O3_5008A"
H1_4862A_kinem = "O3_5008A"

#Ne4_1600A_kinem = "O3_1664A"
#He2_1640A_kinem = "O3_1664A"

Ne4_1600A_kinem = "O3_5008A"
He2_1640A_kinem = "O3_5008A"
O3_1664A_kinem = "O3_5008A"

#H1_4342A_b = "He2_1640A+O3_1664A"
#He2_1640A_kinem = "H1_4862A"
#4364
